
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 22 09:22:16 GMT-06:00 2022
//----------------------------------------------------

package Complementos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Adverbio_Lugar = 9;
  public static final int Adverbio_Tiempo = 13;
  public static final int Interjeccion = 8;
  public static final int Verbo_Singular = 28;
  public static final int Numero = 14;
  public static final int Conjucion_Cordinantes = 12;
  public static final int Adjetivo_Demostrativo = 16;
  public static final int Verbo = 4;
  public static final int Adjetivo_Posesivo = 30;
  public static final int Adverbio_Duda = 11;
  public static final int Numeral_Ordinal = 18;
  public static final int Adjetivo_Calificativo = 15;
  public static final int ERROR = 3;
  public static final int Articulo_Indefinido = 27;
  public static final int Preposicion = 24;
  public static final int Adverbio_Cantidad = 5;
  public static final int Adverbio_Negacion = 23;
  public static final int Adjetivo_Indefinido = 17;
  public static final int Adverbio_Afirmacion = 22;
  public static final int Sustantivo = 2;
  public static final int EOF = 0;
  public static final int Pronombre_Personal = 19;
  public static final int Conjucion_Subordinante = 7;
  public static final int error = 1;
  public static final int Contraccion = 25;
  public static final int Pronombre_Interrogativo = 20;
  public static final int Articulo_Definido = 21;
  public static final int Verbo_Plural = 29;
  public static final int Adverbio_Modo = 6;
  public static final int Numeral_Cardinal = 10;
  public static final int Signo_Puntuacion = 26;
}

